/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import java.sql.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.TableModel;
import net.proteanit.sql.*;
import org.zu.ardulink.Link;
import org.zu.ardulink.RawDataListener;
import gnu.io.SerialPort;
/**
 *
 * @author STAR
 */
public class EditStuRecords extends javax.swing.JFrame implements RawDataListener{

    /**
     * Creates new form EditStuRecords
     */
    SerialPort serialPort;
    public Link link;
    public boolean isSuccessfullyEnrolled = false;
    private final String ENROL_COMMAND = "1";
    private static final int TimeOut=2000;
    private static final int DataRate=115200;
    
    PreparedStatement PS=null;
    Connection conn=null;
    ResultSet RS=null;
    
    public EditStuRecords() {
        initComponents();
        this.setLocationRelativeTo(null);
        showTableData();
        // Register a RawDataListener to receive data from Arduino.
        // A raw data listener receives all messages(analog or digital) received from Arduino.
    }
    
    public void showTableData(){
        try{
             String sql="SELECT * FROM `student_details`";
             PS = MysqlConnect.ConnectDB().prepareStatement(sql);
             RS = PS.executeQuery();
             jTableStu.setModel(DbUtils.resultSetToTableModel(RS));
             
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error!!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUniqueID = new javax.swing.JTextField();
        jTextFieldFirst = new javax.swing.JTextField();
        jTextFieldLast = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonScan = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStu = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRegNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(145, 61, 136));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDIT STUDENT RECORDS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(58, 83, 155));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("UNIQUE ID:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 114, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Last Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 140, 114, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Registration No.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 60, 114, 35);

        jTextFieldUniqueID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUniqueIDMouseClicked(evt);
            }
        });
        jPanel2.add(jTextFieldUniqueID);
        jTextFieldUniqueID.setBounds(130, 20, 144, 35);
        jPanel2.add(jTextFieldFirst);
        jTextFieldFirst.setBounds(130, 100, 144, 34);
        jPanel2.add(jTextFieldLast);
        jTextFieldLast.setBounds(130, 140, 144, 34);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("SCAN FINGERPRINT");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 180, 174, 36);

        jButtonScan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonScan.setForeground(new java.awt.Color(255, 0, 0));
        jButtonScan.setText("SCAN");
        jButtonScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScanActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonScan);
        jButtonScan.setBounds(10, 220, 87, 32);

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setText("ADD User");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd);
        jButtonAdd.setBounds(170, 220, 109, 35);

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setText("DELETE User");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete);
        jButtonDelete.setBounds(90, 270, 109, 32);

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonClear.setText("CLEAR");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear);
        jButtonClear.setBounds(90, 310, 109, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("------->");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 220, 46, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Search by Reg. No.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(327, 11, 132, 34);

        jTextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldsearch);
        jTextFieldsearch.setBounds(463, 11, 340, 34);

        jTableStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegistrationNo.", "First Name", "Last Name", "Fingerprint"
            }
        ));
        jTableStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStu);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(327, 63, 480, 260);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(680, 340, 81, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("First Name:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 100, 114, 34);
        jPanel2.add(jTextFieldRegNo);
        jTextFieldRegNo.setBounds(130, 60, 144, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        AdminFunctions admin = new AdminFunctions();// TODO add your handling code here:
        admin.setVisible(true);
        admin.pack();
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String ID=jTextFieldUniqueID.getText();
        String regno=jTextFieldRegNo.getText();
        String fname=jTextFieldFirst.getText();
        String lname=jTextFieldLast.getText();
        
        if (ID.equals("")){
                JOptionPane.showMessageDialog(null,"UniqueID not given","Incomplete form",JOptionPane.ERROR_MESSAGE);
        }else if(regno.equals("")){
                JOptionPane.showMessageDialog(null,"Registration Number not given","Incomplete form",JOptionPane.ERROR_MESSAGE);
        }else if(fname.equals("")){
            JOptionPane.showMessageDialog(null,"First Name not given","Incomplete form",JOptionPane.ERROR_MESSAGE);
        }else if(lname.equals("")){
            JOptionPane.showMessageDialog(null,"Last Name not given","Incomplete form",JOptionPane.ERROR_MESSAGE);
        }else{
            String sql="INSERT INTO `student_details`(`id`, `reg.no.`, `first_name`, `last_name`) VALUES (?,?,?,?)";
            try {
             PS = MysqlConnect.ConnectDB().prepareStatement(sql);
             PS.setString(1, ID);
             PS.setString(2, regno);
             PS.setString(3, fname);
             PS.setString(4, lname);
                if (PS.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "New Student Record Added Successfully");
                } 
            }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error!!");
            }
         showTableData();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
             String sql="DELETE FROM `student_details` WHERE `reg.no.` = ?";
             PS = MysqlConnect.ConnectDB().prepareStatement(sql);
             PS.setString(1, jTextFieldRegNo.getText());
             PS.executeUpdate();
             JOptionPane.showMessageDialog(null, "Student Record Deleted Successfully");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error!!");
        }
        showTableData();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldUniqueID.setText("");
        jTextFieldRegNo.setText("");
        jTextFieldFirst.setText("");
        jTextFieldLast.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyReleased
        // TODO add your handling code here:
        String tfs=jTextFieldsearch.getText();
        try{
            String sql="SELECT * FROM `student_details` WHERE `reg.no.` LIKE '%"+tfs+"%'";
            PS = MysqlConnect.ConnectDB().prepareStatement(sql);
            RS = PS.executeQuery();
            jTableStu.setModel(DbUtils.resultSetToTableModel(RS));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error!!");
        }
    }//GEN-LAST:event_jTextFieldsearchKeyReleased

    private void jTableStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStuMouseClicked
        // TODO add your handling code here:
        int j = jTableStu.getSelectedRow();
        TableModel table = jTableStu.getModel();
        jTextFieldUniqueID.setText(table.getValueAt(j, 0).toString());
        jTextFieldRegNo.setText(table.getValueAt(j, 1).toString());
        jTextFieldFirst.setText(table.getValueAt(j, 2).toString());
        jTextFieldLast.setText(table.getValueAt(j, 3).toString());
    }//GEN-LAST:event_jTableStuMouseClicked

    private void jButtonScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScanActionPerformed
        // TODO add your handling code here:
        String fprintID=jTextFieldUniqueID.getText();
        //SET UP A CONNECTION TO ARDUINO
        try{
            link = Link.getDefaultInstance();
            link.addRawDataListener(this);
            //1)GET PORT LIST AND TEST IF IT IS EMPTY
            List<String> portList = Link.getDefaultInstance().getPortList(); 
            if (portList != null && portList.size() > 0) {
                String port = portList.get(0);
                System.out.println("Connecting on port: " + port);
                //2)CONNECT TO PORT FOUND WITH GIVEN BAUDRATE/DATARATE
                boolean connected = link.connect(port,DataRate);
                //3)CREATE INFORMATION MESSAGE TO LET YOU KNOW STATUS OF CONNECTION
                if(connected){
                    JOptionPane.showMessageDialog(null,"Arduino Connected");
                    //4)ALLOW ARDUINO TO BOOT (MAKE IT WAIT FOR 2 SECONDS)
                    Thread.sleep(2000);
                    //writeSerial - sends data to serial port. In this case, it will send value 1. To select the enroll process in arduino code.
                    link.writeSerial(ENROL_COMMAND);
                    //WAIT A SECOND
                    Thread.sleep(1000);
                    //sendCustomMessage - Ardulink asks arduino to do something. In this case,******(hmmm...)
                    link.sendCustomMessage(fprintID);
                    //DISCONNECT FROM ARDUINO AFTER 10 SECONDS
                    Thread.sleep(10000);
                    link.disconnect();
                    if(isSuccessfullyEnrolled){
                        JOptionPane.showMessageDialog(null,"Fingerprint Successfully Stored ");
                    }else{
                        JOptionPane.showMessageDialog(null,"Error!!Please Scan again ");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Arduino NOT Connected");
                }
                
            } else {
                System.out.println("No port found!");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
//BOOM! CONNECTION WORKS
    }//GEN-LAST:event_jButtonScanActionPerformed

    private void jTextFieldUniqueIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUniqueIDMouseClicked
        // TODO add your handling code here:
        try {
             String sql="SELECT MAX(`id`)+1 FROM `student_details`";
             PS = MysqlConnect.ConnectDB().prepareStatement(sql);
             RS = PS.executeQuery();
             if(RS.next()){
                 String ID=RS.getString("MAX(`id`)+1");
                 jTextFieldUniqueID.setText(ID);
             }
             JOptionPane.showMessageDialog(null, "Unique ID found");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error!!");
        }
    }//GEN-LAST:event_jTextFieldUniqueIDMouseClicked

    
    /**
     * @param args the command line arguments
     */
    /**public synchronized void serialEvent(SerialPortEvent oEvent) { if (oEvent.getEventType() == SerialPortEvent.DATA_AVAILABLE) { try { String inputLine=input.readLine(); System.out.println(inputLine); } catch (Exception e) { System.err.println(e.toString()); } } }**/
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStuRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStuRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStuRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStuRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStuRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonScan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStu;
    private javax.swing.JTextField jTextFieldFirst;
    private javax.swing.JTextField jTextFieldLast;
    private javax.swing.JTextField jTextFieldRegNo;
    private javax.swing.JTextField jTextFieldUniqueID;
    private javax.swing.JTextField jTextFieldsearch;
    // End of variables declaration//GEN-END:variables

//IMPLEMENTS RAW DATA LISTENER
    @Override
    public void parseInput(String id, int numBytes, int[] message) {
        StringBuilder build = new StringBuilder(numBytes + 1);
        for (int i = 0; i < numBytes; i++) {
            build.append((char) message[i]);
        }
        String msgString = build.toString();
        if (msgString.contains("SUCCESSFULL_ENROL")) {
            //success
            isSuccessfullyEnrolled = true;
        } else {
            //failure
            isSuccessfullyEnrolled = false;
        }
    }
}
